<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Mukta:300,400,700"> 
<link rel="stylesheet" href="public/fonts/icomoon/style.css">
<link rel="stylesheet" href="public/css/bootstrap.min.css">
<link rel="stylesheet" href="public/css/magnific-popup.css">
<link rel="stylesheet" href="public/css/jquery-ui.css">
<link rel="stylesheet" href="public/css/owl.carousel.min.css">
<link rel="stylesheet" href="public/css/owl.theme.default.min.css">
<link rel="stylesheet" href="public/css/aos.css">
<link rel="stylesheet" href="public/css/style.css">